# print(10, 20, 30, sep = "^^", end = "-->")
# print("안녕")
# age = input("몇 살이세요?")
# print("나이가 ",age,"세 이군요")
price = input("가격을 입력하세요")
amount = input("수량을 입력하세요")
salesprice = int(price) * int(amount)
print("판매가격 =", salesprice, "원입니다.")